"""create initial schema

Revision ID: e74b6ef9de8d
Revises:
Create Date: 2026-09-20 20:25:05.773321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e74b6ef9de8d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataupload",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "region", sa.Enum("VOSTOK", "YUGO_VOSTOK", "YUGOTSENTR", name="region"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engineer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "region", sa.Enum("VOSTOK", "YUGO_VOSTOK", "YUGOTSENTR", name="region"), nullable=False
        ),
        sa.Column("start_point_address", sa.String(length=512), nullable=False),
        sa.Column("start_point_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("start_point_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("shift_start", sa.DateTime(), nullable=False),
        sa.Column("shift_end", sa.DateTime(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum("CAR", "PEDESTRIAN", "BICYCLE", "PUBLIC_TRANSPORT", name="vehicle_type"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["upload_id"], ["dataupload.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type_bk",
            sa.Enum(
                "GLOBAL_PROBLEM",
                "ADDITIONAL_ORDER",
                "LOCAL_REQUEST",
                "CONNECTION",
                name="request_type_bk",
            ),
            nullable=False,
        ),
        sa.Column(
            "type_hd",
            sa.Enum(
                "IP_ADDRESS_169",
                "TVE_ENT_OTHER_ERRORS",
                "TVE_ENT_SET_TOP_BOX_REPLACEMENT",
                "EMERGENCY",
                "EQUIPMENT_ADDITIONAL_ORDER",
                "CONNECTION_OR_EQUIPMENT_ORDER",
                "CONNECTION_REQUEST",
                "INFORMATION",
                "SUBSCRIBER_CONVERGENCE",
                "MONITORING",
                "NO_LINK",
                "LOW_SPEED",
                "GIGABIT_SWITCH",
                "CABLE_WORK",
                "DISCONNECTS",
                "PORT_ERROR_GROWTH",
                "ROUTER_REPLACEMENT_BY_TECHNICIAN",
                "TV_SET_TOP_BOX_REPLACEMENT",
                name="request_type_hd",
            ),
            nullable=False,
        ),
        sa.Column(
            "region", sa.Enum("VOSTOK", "YUGO_VOSTOK", "YUGOTSENTR", name="region"), nullable=False
        ),
        sa.Column("district", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("connection_type", sa.Enum("FMC", "FTTB", name="connection_type"), nullable=True),
        sa.Column("is_gigabit", sa.Boolean(), nullable=False),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_end", sa.DateTime(), nullable=False),
        sa.Column("norm_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("norm_minutes_without_travel", sa.SmallInteger(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column(
            "required_skill",
            sa.Enum("LOCAL_WORKS", "CONNECTION_AND_ORDERS", "EMERGENCY_WORKS", name="skill"),
            nullable=False,
        ),
        sa.Column(
            "required_vehicle_type",
            sa.Enum("CAR", "PEDESTRIAN", "BICYCLE", "PUBLIC_TRANSPORT", name="vehicle_type"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("priority between 1 and 3", name="ck_request_priority"),
        sa.ForeignKeyConstraint(["upload_id"], ["dataupload.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "uploadedfile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("s3_bucket", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["upload_id"], ["dataupload.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_table(
        "engineerskill",
        sa.Column("engineer_id", sa.UUID(), nullable=False),
        sa.Column(
            "skill",
            sa.Enum("LOCAL_WORKS", "CONNECTION_AND_ORDERS", "EMERGENCY_WORKS", name="skill"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engineer_id"], ["engineer.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("engineer_id", "skill"),
    )
    op.create_table(
        "replanningevent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "region", sa.Enum("VOSTOK", "YUGO_VOSTOK", "YUGOTSENTR", name="region"), nullable=False
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "URGENT_REQUEST",
                "REQUEST_CANCELLED",
                "ENGINEER_UNAVAILABLE",
                name="replanning_event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("engineer_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "request_id is not null or engineer_id is not null", name="ck_replanning_event_target"
        ),
        sa.ForeignKeyConstraint(["engineer_id"], ["engineer.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["request_id"], ["request.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "region", sa.Enum("VOSTOK", "YUGO_VOSTOK", "YUGOTSENTR", name="region"), nullable=False
        ),
        sa.Column("upload_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("INITIAL", "MANUAL_REPLAN", "EVENT_REPLAN", name="plan_kind"),
            nullable=False,
        ),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.Column("based_on_plan_id", sa.UUID(), nullable=True),
        sa.Column("triggered_by_event_id", sa.UUID(), nullable=True),
        sa.Column("total_mileage_km", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column("engineers_used_count", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind != 'EVENT_REPLAN' or triggered_by_event_id is not null",
            name="ck_plan_event_replan_has_event",
        ),
        sa.ForeignKeyConstraint(["based_on_plan_id"], ["plan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["triggered_by_event_id"], ["replanningevent.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["upload_id"], ["dataupload.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "planstop",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("engineer_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.SmallInteger(), nullable=False),
        sa.Column("planned_arrival", sa.DateTime(), nullable=False),
        sa.Column("travel_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["engineer_id"], ["engineer.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_id"], ["request.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "engineer_id", "sequence_number", name="uq_plan_stop_order"),
        sa.UniqueConstraint("plan_id", "request_id", name="uq_plan_stop_request"),
    )
    op.create_table(
        "planunassignedrequest",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "NO_MATCHING_SKILL",
                "NO_MATCHING_VEHICLE",
                "NO_TIME_SLOT",
                "NO_AVAILABLE_ENGINEER",
                name="unassigned_reason",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_id"], ["request.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "request_id", name="uq_plan_unassigned_request"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planunassignedrequest")
    op.drop_table("planstop")
    op.drop_table("plan")
    op.drop_table("replanningevent")
    op.drop_table("engineerskill")
    op.drop_table("uploadedfile")
    op.drop_table("request")
    op.drop_table("engineer")
    op.drop_table("dataupload")
    op.execute("DROP TYPE IF EXISTS unassigned_reason")
    op.execute("DROP TYPE IF EXISTS plan_kind")
    op.execute("DROP TYPE IF EXISTS replanning_event_type")
    op.execute("DROP TYPE IF EXISTS skill")
    op.execute("DROP TYPE IF EXISTS connection_type")
    op.execute("DROP TYPE IF EXISTS request_type_hd")
    op.execute("DROP TYPE IF EXISTS request_type_bk")
    op.execute("DROP TYPE IF EXISTS vehicle_type")
    op.execute("DROP TYPE IF EXISTS region")
    # ### end Alembic commands ###
